myproject/apps/book/urls.py
from django.urls import path

from . import views

app_name = 'book'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:article_id>/', views.detail, name='detail'),
    path('add', views.add, name='add'),
    path('add_book', views.add_book, name='add_book')
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('book/', include('apps.book.urls')),
]

myproject/apps/book/models.py
import datetime
from django.db import models
from django.utils import timezone


class Book(models.Model):
    book_title = models.CharField('название книги', max_length=200)
    book_author = models.CharField('автор книги', max_length=200)
    book_description = models.TextField('Описание книги')
    pub_date = models.DateField('дата публикации')

    def __str__(self):
        return self.book_title

    class Meta:
        verbose_name = 'Книга'
        verbose_name_plural = 'Книги'



myproject/apps/book/views.py
from django.http import Http404, HttpResponseRedirect
from django.http import HttpResponse
from django.shortcuts import render
from .models import Book
from django.urls import reverse


def index(request):
    latest_book = Book.objects.order_by('book_title')
    return render(request, 'book/list.html', {'latest_book': latest_book})


def detail(request, article_id):
    try:
        a = Book.objects.get(id=article_id)
    except:
        raise Http404("Книга не найдена")
    return render(request, 'book/detail.html', {'book': a})


def add(request):
    return render(request, 'book/add.html')


def add_book(request):
    print(request.POST)
    a = Book(book_title=request.POST['title'], book_author=request.POST['author'],
             book_description=request.POST['description'],
             pub_date=request.POST['date']
             )
    a.save()
    return HttpResponseRedirect(reverse('book:index'))

myproject/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Мой сайт{% endblock %}</title>
</head>
<body>

   {% block content %}{% endblock %}

</body>
</html>

myproject/templates/book/add.html
{% extends 'base.html' %}

{% block title %}Добавление новой книги{% endblock %}

{% block content %}
 <form action="{% url 'book:add_book' %}" method="post">
     {% csrf_token %}
     <input type="text" required placeholder="Название книги" name="title"><br>
     <input type="text" required placeholder="Автор книги" name="author"><br>
     <input type="date" required placeholder="Дата публикации" name="date"><br>
     <textarea type="text" required placeholder="Описание книги" name="description"></textarea><br>
     <button type="submit">Добавить книгу</button>
 </form>
{% endblock %}

myproject/templates/book/detail.html
{% extends 'base.html' %}

{% block title %}{{book.book_title}}{% endblock %}

{% block content %}
<h2>{{book.book_title}}</h2>
<em>{{book.book_author}}</em>
<p>{{book.book_text}}</p>
<em>{{book.pub_date}}</em>
<hr>
<hr>


{% endblock %}

myproject/templates/book/list.html
{% extends 'base.html' %}

{% block title %}Список книг{% endblock %}

{% block content %}
   {% if latest_book %}
      {% for a in latest_book %}
          <p>
         <a href="{% url 'book:detail' a.id %}">{{a.book_title}}</a>
            </p>
      {% endfor %}
   {% else %}
      Книг нет
   {% endif %}
   <br>
   <hr>
   <a href="{% url 'book:add' %}"> Добавить книгу </a>
{% endblock %}